# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

parameters:
  - name: tags
    type: string
    displayName: Tags a ejecutar
  - name: env
    type: string
    displayName: Ambiente a ejecutar
    values:
      - 'dev'  

variables:
  - name: vmImage
    value: 'windows-latest'
    readonly: true

stages:
  - stage: Execute_Tests
    displayName: Execute automated tests
    jobs:
      - job: Job
        pool:
          vmImage: $(vmImage)
        steps:
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '11'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'
          - script: |
              cd serenity-screenplay-training
              mvn clean install -DskipTests
            displayName: 'Build'  
          - script: |
              cd serenity-screenplay-training
              mvn clean verify "-Dcucumber.filter.tags=${{ parameters.tags }}"
            displayName: 'Execute tests'
          - task: PublishPipelineArtifact@1
            condition: always()
            inputs:
              targetPath: '$(Pipeline.Workspace)/s/target/site/serenity'
              artifact: 'SerenityReport'
              publishLocation: 'pipeline'
            displayName: 'Publish report'
          - task: PublishTestResults@2
            condition: always()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**TEST-*.xml'
              searchFolder: '$(System.DefaultWorkingDirectory)'
              publishRunAttachments: true
            displayName: 'Publish tests result'